#!/bin/bash

# Define the local configuration file that should be used by nvc++
LOCALRC="/home/nwachuch/bld6/nvcpp-tests/actscore-issue-recreation/localrc_gcc112"
if [[ ! -f $LOCALRC ]]; then
    echo "nvc++_p ERROR: no local rc file \"$LOCALRC\" found"
    exit 1
fi
LOCALRC="-rc=${LOCALRC}"

# Initialize path to compilers based on system default
NVCPP=$( which nvc++ )
CXX=$( which g++ )

# Parse arguments
args=$*

# Check parameter existences which determines if nvc++ is used as compiler
is_any_in_args(){
  for arg in "$@"
  do
    # check if current argument is present in string of arguments
    echo "$args" | grep -q "$arg"
    if [[ $? -eq 0 ]]; then
      return 0
    fi
  done
  return 1
}

# declare files to be compiled with nvc++
NVCPP_DIRS=(
    "TestActsCore.dir"
    "ActsCore.dir"
)
# Prepare compiler args for nvc++ or g++
if is_any_in_args "${NVCPP_DIRS[@]}"; then
    echo ""; echo "******************************"
    echo "Use NVC++ COMPILER"
    echo "******************************"; echo ""

    STDPAROPTS="-cudalib=curand"

    # remove compiler flags not supported by nvc++
    X=$( echo $args | sed s/-pipe// )
    X=$( echo $X | sed s/-Wno-unused-local-typedefs// )
    X=$( echo $X | sed s/-Wunused-local-typedefs// ) # TODO: newly added, verify if no side effects
    X=$( echo $X | sed s/-Woverloaded-virtual// )
    X=$( echo $X | sed s/-fdiagnostics-color=always// )
    X=$( echo $X | sed s/gnu++17/c++17/ )

    ## needed for CMAKE_RELEASE_TYPE=Debug
    X=$( echo $X | sed s/-fsanitize=undefined// )
    X=$( echo $X | sed s/-g3// ) # TODO newly added
    X=$( echo $X | sed s/-Werror// ) # TODO newly added: should only be temporary until dependencies have fixed the "no new line warnings"

    ## get an undefined cudaGetDevice
    X=$( echo $X | perl -ne '@X=split(" ",$_); @Y=map(/libcudart_static.a/ ? () : $_, @X); print "@Y"' )
    X=$( echo $X | sed s/-lcudart_static// )


    CXX=${NVCPP}
    CXXARGS="$LOCALRC $STDPAROPTS $X"
    
else
    args=$( echo $args | perl -ne '@X=split(" ",$_); @Y=map(/libcudart_static.a/ ? () : $_, @X); print "@Y"' )

    CXXARGS=$args
fi


## ubsan needed for Debug
if [[ $DBG -eq 1 ]]; then    
    DBGOPTS=" -lubsan"
fi

CXXARGS+=$DBGOPTS

if [[ ! -z ${NVCPP_VERBOSE+set} ]]; then
    echo "==> $CXX $CXXARGS"
fi

$CXX $CXXARGS
